# Generated by GitHub Copilot based on the provided SQL schema

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("idUsuario", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=40)),
                ("apellido", models.CharField(max_length=40)),
                ("correo", models.EmailField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=150)),
                ("fechaNacimiento", models.DateField()),
            ],
            options={"db_table": "Usuario"},
        ),
        migrations.CreateModel(
            name="Materiales",
            fields=[
                ("idMaterial", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=150)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unidad", models.CharField(max_length=50)),
            ],
            options={"db_table": "Materiales"},
        ),
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                ("idProyecto", models.AutoField(primary_key=True, serialize=False)),
                ("titulo", models.CharField(max_length=100)),
                ("descripcion", models.CharField(max_length=250)),
                ("fechaCreacion", models.DateField()),
                (
                    "usuario",
                    models.ForeignKey(
                        db_column="idUsuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proyectos",
                        to="core.usuario",
                    ),
                ),
            ],
            options={"db_table": "Proyecto"},
        ),
        migrations.CreateModel(
            name="Planos",
            fields=[
                ("idPlano", models.AutoField(primary_key=True, serialize=False)),
                ("archivo", models.TextField()),
                ("estado", models.CharField(max_length=50)),
                ("datosVectoriales", models.JSONField(blank=True, null=True)),
                ("fechaSubida", models.DateTimeField(auto_now_add=True)),
                (
                    "proyecto",
                    models.ForeignKey(
                        db_column="idProyecto",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planos",
                        to="core.proyecto",
                    ),
                ),
            ],
            options={"db_table": "Planos"},
        ),
        migrations.CreateModel(
            name="Ambientes",
            fields=[
                ("idAmbiente", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("areaM2", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "plano",
                    models.ForeignKey(
                        db_column="idPlano",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ambientes",
                        to="core.planos",
                    ),
                ),
            ],
            options={"db_table": "Ambientes"},
        ),
        migrations.CreateModel(
            name="Presupuesto",
            fields=[
                ("idPresupuesto", models.AutoField(primary_key=True, serialize=False)),
                (
                    "costoTotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("fechaGeneracion", models.DateTimeField(auto_now_add=True)),
                (
                    "plano",
                    models.ForeignKey(
                        db_column="idPlano",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presupuestos",
                        to="core.planos",
                    ),
                ),
            ],
            options={"db_table": "Presupuesto"},
        ),
        migrations.CreateModel(
            name="ItemsPresupuesto",
            fields=[
                (
                    "idItemsPresupuesto",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "cantidadCalculada",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "precioUnitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("subTotal", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "material",
                    models.ForeignKey(
                        db_column="idMaterial",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items_presupuesto",
                        to="core.materiales",
                    ),
                ),
                (
                    "presupuesto",
                    models.ForeignKey(
                        db_column="idPresupuesto",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.presupuesto",
                    ),
                ),
            ],
            options={"db_table": "itemsPresupuesto"},
        ),
        migrations.CreateModel(
            name="AlertasAuditoria",
            fields=[
                (
                    "idAlertasAuditoria",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("tipo", models.CharField(max_length=50)),
                ("mensaje", models.TextField()),
                ("fechaAnalisis", models.DateTimeField(auto_now_add=True)),
                (
                    "presupuesto",
                    models.ForeignKey(
                        db_column="idPresupuesto",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertas_auditoria",
                        to="core.presupuesto",
                    ),
                ),
            ],
            options={"db_table": "alertasAuditoria"},
        ),
    ]
